### ISSUE TITLE
./flattablesc outout paths are very confusing. See suggestions in the make file

### ISSUE THREAD

**Issue by ghost** [urban-wombat/flattables#3]
Problem:
Output paths are ambiguous.
See Case 1 and Case 2 in the MakeFile to see how ambiguous it is currently.

Reproduce:
Everything need to reproduce is in the Makefile. Use any .got table you want as it does not matter.

Suggested Fix:
The suggestion is to make all input and output paths absolute. Its just easier for everyone.
Also, for the output sample, maybe use the convention of "cmd/PACKAGENAME/main.go" also, because everyone gets thats approach with golang and there is no guessing the main file.

I also think that absolute paths and absolute golang namespaces will make it much easier for your inside your code generator - everything is very clear then ?
I did not check if flatc also takes absolutes paths ! If it does then you have absolute paths everywhere and so would make things easy.
It allows the user to have fully control. Eventually best practice approach for where things should be placed in relation to the .got will become apparent but for now full control feels best.
For example best practice is to just take where ever the .got is and make a gen folder under it with a cmd and pkg folder. Sample goes in the cmd. Code goes in the pkg. But still not sure, so just let user control it all for now.

MakeFile
```
# user walk through of using it. 
# tools are in $BIN_FSPATH

BIN_FSPATH=$(realpath $(PWD)/../tools/bin)

NAME=mypackage
NAMESPACE=github.com/gedw99/ci/server/compute/flatbuffers/$(NAME)

# Path to .got files.
INPUT_FSPATH=$(GOPATH)/src/$(NAMESPACE)

# Currently, the generator gives no control about output path.
#OUTPUT_FSPATH=$(realpath $(PWD)/../$(NAME)_main)
# Currently, the generator give no control about sample output path.
# Hard codes to Case 2 location for now :) 
SAMPLE_OUTPUT_FSPATH=$(GOPATH)/src/$(NAMESPACE)_main

SAMPLE_OUTPUT_MAIN=$(NAME)_main.go

print:
	@echo 
	@echo BIN_FSPATH : 				$(BIN_FSPATH)
	@echo NAME : 					$(NAME)
	@echo NAMESPACE : 				$(NAMESPACE)
	@echo INPUT_FSPATH : 			$(INPUT_FSPATH)
	@echo OUTPUT_FSPATH : 			$(OUTPUT_FSPATH)
	@echo SAMPLE_OUTPUT_FSPATH : 	$(SAMPLE_OUTPUT_FSPATH)
	@echo SAMPLE_OUTPUT_MAIN : 		$(SAMPLE_OUTPUT_MAIN)
	@echo

check:
	$(BIN_FSPATH)/gotsyntax tables.got

gen-help:
	cd $(BIN_FSPATH) && ./flattablesc -h

gen:
	# BUG:
	# Cant control OUTPUT path :) Its also a bit weird the way it chooses where to put the OUTPUT_FSPATH and SAMPLE_OUTPUT_FSPATH.
	# Try the two approaches belwo to see what i mean...
	# Suggested Fix is to always use absolute path. Its makes everything clearer from the get go for everyone. 
	# - 1. Make the Output and Sample Output paths absolute ( controlled by user)
	# - 2- Make the Input path absolute ( controlled by user currently )
	# Case 1:
	# In this case it puts the OUTPUT one folder above where the BINPATH is. It disregards the INPUT_FSPATH as context for where the OUTPUT path will be.
	#cd $(BIN_FSPATH) && ./flattablesc -v -f $(INPUT_FSPATH)/tables.got -n $(NAME) -p $(NAMESPACE)

	# Case 2:
	# In this case it puts the OUTPUT in the same folder as the INPUT_FSPATH and then the OUTPUT sample on foler above the OUTPUT. Completely different from Case 1.
	$(BIN_FSPATH)/flattablesc -v -f $(INPUT_FSPATH)/tables.got -n $(NAME) -p $(NAMESPACE)

gen-clean:
	# delete output (Case 2)
	cd $(INPUT_FSPATH) && rm -rf *.go
	cd $(INPUT_FSPATH) && rm -rf *.fbs

	# delete sample output (Case 2)
	rm -rf $(SAMPLE_OUTPUT_FSPATH)

run:
	cd $(SAMPLE_OUTPUT_FSPATH) && go run $(SAMPLE_OUTPUT_MAIN)


```

**Comment by urban-wombat** [comment]
Hi Gerard

It'll be a couple of days before I can get to it.

I'll reproduce with your Makefile (thanks for designing and documenting it
so clearly) and I think I'll run
through with you the fixes before implementing them.

Cheers, Malcolm

**Comment by urban-wombat** [comment]
Hi Gerard

Merry Christmas to you and yours!

main programs are now under their relevant cmd directory:

   - github.com/urban-wombat/gotables/cmd/gotecho/gotecho.go
   - github.com/urban-wombat/gotables/cmd/gotsyntax/gotsyntax.go
   - urban-wombat/flattables/cmd/flattablesc/flattablesc.go

flattablesc now has the following new optional flags:

   - [-o] <out-dir> Where to put generated Go code files. Default is
   ../<namespace>
      - Note: The tail end of <out-dir> must match -p <package-name>
      - [-s] <out-dir-main> Where to put generated sample main Go code
   file. Default is <out-dir>/cmd/<package-name>
   - [-d] Dry run (also turns on verbose)

By default flattables_sample_main.go with go under
<out-dir>/cmd/<package-name> but you can put it anywhere.

The location of <out-dir> is more restricted. It has to go somewhere under
your package hierarchy. And it must
match (at the tail end) the <package-name>. If it doesn't, it seems the
package cannot be found, by e.g., main.go.

That essentially means that the -o option is redundant because the location
can be calculated from -p <package>
So -o might be up for the chopping block already.

I will attach a run.sh script which lines up the names vertically and
clarifies the relationships.

Cheers, Malcolm

**Comment by gedw99** [comment]
@urban-wombat 
Thank Malcolm. This looks really thorough. Will kick the tires and feedback

**Comment by urban-wombat** [comment]
Hi Ged

Good to hear from you.

There's a fair amount of tread on those tyres. If you find any nails, let
me know.

Cheers, Mal
